
CFLAGS += -std=c++11 -pthread -g -O3 -I$(ROOT)/include
LDFLAGS += -L/usr/local/lib

SRC := $(wildcard *.cpp)
OBJ := $(SRC:%.cpp=bin/%.o)
OBJDIRS := bin
DEPS := $(OBJ:.o=.d)

-include $(DEPS)

bin/%.o: %.cpp
	$(CC) $(CFLAGS) -MMD -MP -MF $(patsubst %.o,%.d,$@) -c -o $@ $<

$(OBJ): | $(OBJDIRS)

$(OBJDIRS):
	mkdir -p $(OBJDIRS)
