
CFLAGS = -std=c++11 -g -O0
INC := -I$(ROOT)/include

SRC := $(wildcard *.cpp)
OBJ := $(SRC:%.cpp=bin/%.o)
OBJDIRS := bin
DEPS := $(OBJ:.o=.d)

-include $(DEPS)

bin/%.o: %.cpp
	$(CC) $(CFLAGS) $(INC) -MMD -MP -MF $(patsubst %.o,%.d,$@) -c -o $@ $<

$(OBJ): | $(OBJDIRS)

$(OBJDIRS):
	mkdir -p $(OBJDIRS)
